repos:
- repo: local
  hooks:
  - id: ruff-lint
    name: ruff-lint
    language: system
    types:
      - python
    entry: make ruff-lint
    pass_filenames: false

  - id: ruff-format
    name: ruff-format
    language: system
    types:
      - python
    entry: make ruff-format
    pass_filenames: false

  - id: mypy
    name: mypy
    language: system
    types:
      - python
    entry: make mypy
    pass_filenames: false

